### ISSUE TITLE
Angel Ring Stil not Craftable, the Cursed Lasso has wrong NBT Data

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/Foolcraft_3#121]
## Modpack Information
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [X] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
The Angel Ring Recipe still isn't found, What I noticed is that the Ghast shows different Health Values for me, max HP were Ranging from 10 to 12 in my tests.

## Reproduce Steps
Try and build an angel ring.

**Comment by Mrbysco** [comment]
Are you using redisturbed spawners? As the mobs that spawn from those have more health than normal mobs have.

**Comment by Mrbysco** [comment]
Seems like the difficulty level of your world influences the amount of health the ghast has.

**Comment by ChromeMystic** [comment]
I play on hard, but caught the Ghast in the wild. I will try again later lowering the dificulty :)

**Comment by GhostCatcherSky** [comment]
I can't craft the Angel ring or the energy condenser.  I see in JEI it says 4.0/8.0 for the ghast's health.  I am playing on normal and the ghast spawns with 10.0 health.  I was in a creative test world and spawned in the ghast myself using the egg lowered the health to all possibilities and it still wouldn't work.  I used the summon command, auto spawner, and rf tools spawner and none of it worked.  This sucks because progression wise I have done literally everything else.  energy condenser is all that I have left to start making and trying to progress with.

**Comment by oacaptain** [comment]
Same here with the ring here are some pictures, nothing!!
![2018-06-08_22 16 55](https://user-images.githubusercontent.com/34013573/41200926-49b1ad68-6cb6-11e8-9a5f-cbc771e18ab1.png)
![2018-06-08_22 18 05](https://user-images.githubusercontent.com/34013573/41200927-49d5e7be-6cb6-11e8-9204-386a1832480f.png)

**Comment by Mrbysco** [comment]
Scalda is aware of the issue and is gonna fix it next version

**Comment by GhostCatcherSky** [comment]
fix it in the next version? ughhh.. I was waiting for 1.3.0 to come out because that is what I was told was gonna fix combination crafting.  is it just the angel ring or literally every item you can make with the crafting besides the energy condenser mk2? the energy condenser mk2 is craftable but the energy condenser mk1 isn't

**Comment by Mrbysco** [comment]
This issue has been fixed in 1.3.1.
Quoting from the changelog: "	You no longer need the ghast and bat in the lassos but you need a couple statues now instead"
