### ISSUE TITLE
Foolcraft forge server .jar does not launch correctly

### ISSUE THREAD

**Issue by AlcoxDape** [scalda/Foolcraft_3#132]
## Modpack Information
- [x ] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [ ] In single player
     - [ x] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x ] I am crashing and can provide my crash report(s)
- [x ] I have not altered the modpack [if you have, note the removed mods/added mods/changes in Additional Information]

## Issue Description
running the "forge-1.12.2-14.23.4.2705-universal.jar" file (server file) causes an error

## Reproduce Steps
literally just running the server .jar
 https://pastebin.com/9u0qv8H5

**Comment by Mrbysco** [comment]
You need to run it with parameters. Otherwise it will run out of memory.

You could do so by creating a text file, putting the following in and saving the text file as startserver.bat. (This creates a Batch file) [if using windows that is]
`java -server -Xms%%%M -Xmx%%%M -jar forge-1.12.2-14.23.4.2705-universal.jar nogui
`
Where %%% in -Xms%%%M is the minimal amount of memory and the %%% in -Xmx%%%M amount of memory. (Change the %%% with the amount of memory in MB)

**Comment by scalda** [comment]
the server files now come with a start up batch file to run the forge server
