### ISSUE TITLE
Replace veinminer with Ore Excavation

### ISSUE THREAD

**Issue by yamy19** [scalda/Foolcraft_3#167]
## FEATURE REQUEST
- [x] I would like to propose an additional mod.
- [ ] I would like to propose a config change.
- [ ] I would like to propose a custom recipe.
- [ ] I would like to propose another change.

## MOD INFORMATION
Ore Excavation

https://minecraft.curseforge.com/projects/ore-excavation

**Comment by kpeckett** [comment]
From my experience, they work the same, at least from a user's perspective. What improvements do you think OE would add over VM?

**Comment by yamy19** [comment]
ore-excavation has the ability to blacklist blocks from being mined using veinminer

**Comment by yamy19** [comment]
because as of right now if you run a spongeforge server and multiple players use veinminer on either redstone ore or coal ore then the server will hang

**Comment by scalda** [comment]
Then you would need to make those changes on your sides this will not change within the pack

**Comment by theBluebaerry** [comment]
I think people are missing the point here, the reason Yamy is suggesting the change is because the blacklists in the veinminer configs _do not _work.__ As I believe you have posted something about yourself Scalda in regards to the tool blacklist. Yes this new mod works exactly the same as a user, but as a server owner or modpack dev *cough cough* having a functional whitelist/blacklist (toggleable) is pretty damn important...

**Comment by scalda** [comment]
this won't get changed as iskall prefers veinminer over OE
