### ISSUE TITLE
World stopped working

### ISSUE THREAD

**Issue by Meaffjo** [scalda/Foolcraft_3#207]
## Issue Description
If I join my singleplayer world the world does nothing i can move but other entitys cant. If i break a block it will not drop. Also blocks will not update. For example if i break a block under a pressure plate the pressure plate will not pop off.

## Reproduce Steps
Join a world

## Additional Information
https://imgur.com/fzR5WXZ
https://imgur.com/a/lYNywde
https://imgur.com/a/kwcQVPa

**Comment by Mrbysco** [comment]
Logs please. also please fill in the pack version you are using

**Comment by Meaffjo** [comment]
Im using the newest version (1.4.5)
[latest.log](https://github.com/scalda/Foolcraft_3/files/2197675/latest.log)

**Comment by jlipscomb** [comment]
What are your computer specs? Mainly, do you have 9 or more Gigabyes of RAM?

I am taking a stab in the dark, and this could not be the root cause of your issues. I am wondering if you have over allocated memory to the JVM. If that is the case, then IO can cause issues. This is because it would have to cache things to the disk, then recall it back to RAM. 

It looks like you are chunk loading a good bit of areas as well, which is why I am wondering if this is the case.

**Comment by Meaffjo** [comment]
I have a 8700K and a GTX 960. I have in the Minecraft launcher by JVM arguments Xmx9216m standing. Before the update i didnt had any performance issues.

**Comment by benhavo** [comment]
I'm having the same issue. I've tried modifying the memory allocation from 6G to 9G in .5G increments. My logs are benign, and look similar to OP with less chunk loading. Any updates or solutions?

**Comment by benhavo** [comment]
FYI, I just removed mob_grinding_utils and everything the world is running normally again. Maybe give that a try

**Comment by scalda** [comment]
update to beta 1.5 and it will all work again
