### ISSUE TITLE
Constant crash suddnely on world load.

### ISSUE THREAD

**Issue by strivingpig97** [scalda/Foolcraft_3#253]
## Reproduce Steps
whenever i load up my world i get a crash with a crash log
[crash.log](https://github.com/scalda/Foolcraft_3/files/2238572/crash.log)

## Additional Information
I have removed foamfix as i was getting a crash and removed the hats mod as i believe this was also giving me a crash. I beleieve its a driver issue but cannot find any fix and im still not 100% certain. Also, ive allocated 10gb of ram through the twitch launcher.

**Comment by PGamerMC** [comment]
I get the exact same crash but with thermal foundation and ae2 stuff

**Comment by MultipleMean150** [comment]
First, I'd recommend updating your java.  Looks like you have an old version.  Then I'd recommend that yo allocate no more than 6GB RAM in your launcher.

**Comment by xGarionx** [comment]
That one should be gone with updated java to the lates version and if the issue prevails set your java classpath again in your OS settings . (it has nothing to do with allocated ram, as long as you have enough ram to let your OS run comfortable)

**Comment by TheMajesticPickle** [comment]
To those of you saying he needs to update his java version— it looks like he’s running 8u 51, this is almost certainly intentional. Certain graphics drivers, mainly integrated graphics, can only run minecraft on java version below 8u60(see: http://hopper.minecraft.net/help/pixel-format-not-accelerated/) , and the version below 8u60 is 8u51, from 2015. I’m one of them, however 8u51 only seems to apply to the jar launcher. This dated version of java does cause issues, and there’s bugs with it, but unfortunately I dont know if any version above 8u51 works. 

As for OP, try using the FTB legacy launcher. It may suck but you might just have to deal with it. I wouldn’t recommend multimc unless the ftb launcher doesnt work. Best of luck

Edit: apparently FC3 isn't on the ftb launcher at all, try multimc. otherwise I don't know. let me know if you come up with something, as Im having this issue in other modpacks as well

**Comment by scalda** [comment]
Has this been sorted. please respond/close the issue or i will close in 7 days

**Comment by strivingpig97** [comment]
Nothing really seems to fix the problem im having. I really apredciate the help
