### ISSUE TITLE
Chunkloading issues with old FTB Utilities version

### ISSUE THREAD

**Issue by TheSpicePhantom** [scalda/Foolcraft_3#264]
Hi, I'm an Admin on a public server that's hosting Foolcraft 3. We noticed FTBU running 6 versions behind which may have had problems with chunkloading at that time.

We are using the latest version of the pack. 
Thanks

**Comment by itskdog** [comment]
Chunk loading from FTBU should be disabled by default in FC3 because of the bugs. The recommended chunk loader is the weirding gadget, which is designed to be efficient for servers.
________________________________

**Comment by nzminecraftDOTcom** [comment]
I've had to shut chunk loading off, we had way too many players loading chunks and the server was unplayable. The old version may be due to compatibility issues with other mod versions. EnderIO has just released a fix for those who use Spongeforge, and the newest version clashes with Refined Storage.

**Comment by scalda** [comment]
update to Beat 1.5 and test, Please report back and close the issue if it's solved. i will close in 7 days if not responded to or not closed before hand
