### ISSUE TITLE
Wireless Crafting Terminal calculating autocraft job forever with >1 CPU

### ISSUE THREAD

**Issue by Revvilo** [scalda/Foolcraft_3#286]
## Modpack Information
* Current Pack Version: 1.5.1
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I have not altered the modpack

## Issue Description
With more than one crafting CPU (afaik is just a cube of crafting storage, co-processors and such) - the Wireless Crafting Terminal from _Wireless Crafting Terminal 2_ will just sit on `Crafting Plan -- Calculating Please Wait...` forever.

## Reproduce Steps
- Get a **W**ireless **C**rafting **T**erminal working
  - Using a security terminal - link it to the network
  - Add a wireless access point to allow connection
- Create two crafting CPUs on the network
  - In my case I just used two _separate_ **64k Crafting Storage** blocks. Any type will work
- Get an interface and place any encoded pattern into it
- Request any amount of said pattern from the WCT and hit `Next`
  - You don't need the materials stored for the recipe
- Observe

Here is my setup in creative for reference;

<img src="https://user-images.githubusercontent.com/13816212/44705338-74039700-aaf2-11e8-9def-c67b63ba9534.png" width="250">

#### Modpack Changes (1.5.1)
- Added Optifine

**Comment by infogulch** [comment]
I am also encountering this after updating from 1.4.5 to 1.5.1.

**Comment by infogulch** [comment]
Ok this is weird. In the release logs for 1.5.1 it looks like the WCT version was *downgraded*:

    Wireless Crafting Terminal (went from WirelessCraftingTerminal-1.12.2-3.9.71.jar to WirelessCraftingTerminal-1.12.2-3.9.67.jar)

This might be a release issue with WCT, because it looks like .67 is the latest stable, but it was released *after* .71 .., or something?  The releases of WCT are just kinda confusing in general: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files

I'm not familiar with the releases and mod choices, so I really don't know what the latest version is or if there was a reason for downgrading (or upgrading? I still can't tell), but it looked strange to me. I have reproduced this with only the WCT mod and will be posting an issue on their bug tracker.

**Comment by infogulch** [comment]
Ok it looks like this was a compatibility issue. WCT has released a new version that is compatible with a new version of AE2 (see referenced issue).

Can we get an update with AE2 rv6 alpha 4 and WCT 3.10.80?

**Comment by Revvilo** [comment]
That's awesome man! I appreciate the work you put into getting this resolved. Been pretty awkward trying to use one CPU this whole time, hehe.
Getting an update to the mod would be great. But for now, I think a little manual updating is in order 😉

**Comment by scalda** [comment]
working on 1.5.3 now should be out by Monday i hope
