### ISSUE TITLE
My friends inventory just disapear, waypoints, homes, but advancments stayed how can i fix this?

### ISSUE THREAD

**Issue by MineForFunCraft** [scalda/Foolcraft_3#293]
Hey, so i run in to problem few days ago, i launched my server for my friend and this happened, his invetory, waypoints, homes all gone, but advancements stayed is there anything from the server side that i can fix this? and a bit off topic how to update server from 1.4.5 to 1.5.1?

**Comment by nzminecraftDOTcom** [comment]
Utilise a backup that you have, that'll be the only way to get back a deleted player inventory/file

**Comment by Revvilo** [comment]
I've seen this happen on a LAN world that I ran; where the player that joined had somehow ended up with another UUID and thus the server thought he was a different player. It was fixed by him relaunching his game. - Not sure if that will help or not, but I thought I'd put it out there.
Losing waypoints is probably unrelated, as they are stored client side and are saved under the name that is given to the server in the `Multiplayer` menu. So if you change the name, you end up with a new waypoint & map folder. (Under `Journeymap` in the modpack dir)

As far as updating the server, all I do is look at the folders inside the `Server Files` download for the new version of the pack, **move** the matching folders out of the **existing server** - over to a backup or whatnot - and copy the ones from the **new** `Server Files` download into the server - effectively swapping the old folders.
Normally those folders consist of `Mods`, `Config`, `Scripts` and `Libraries` from what I remember.
