### ISSUE TITLE
Frosty Generator crash while shift clicking in snowballs

### ISSUE THREAD

**Issue by Moukit13** [scalda/Foolcraft_3#353]
## Issue Description
Heya! I've started up an automatic power supply with frosty generators and snow golems, (which works amazingly btw) but things get a little tricky when I try to add snowballs manually. if i shift click in snowballs with even just one in the generator it lags, and if the stack numbers added together equals more than 16, the game freezes up. also included in the png file is an error that's popping up, was wondering if that's unique to me or if others are getting it too, and either way if i should worry about it.

![foolcraft frosty setup](https://user-images.githubusercontent.com/55463779/65079891-1268d180-d96e-11e9-9a4f-08b440241512.PNG)

## Reproduce Steps
1.have a frosty generator with a partial stack of snowballs in it
2.shift click in an amount of snowballs that will fill the stack past 16. (max stack size for snowballs, for those of you who don't know)
3.experience java trying to figure out what just happened XD

## Additional Information
i don't know where to find the crash reports, but will provide them if you can tell me where they are. i've tried to find them, but to no avail.

**Comment by Revvilo** [comment]
Is your game crashing with Vanillafix telling you so then letting you back to the main menu, or is the game just freezing and requiring a force-close to get out of? If it's just freezing then you don't have to worry about crash reports because none will be generated.
The pack has gone long undeveloped now so I wouldn't expect a fix for it, but you could of course update the mods yourself as it's probably just a bug in Thermal Expansion.

In order to find the crash reports you can just go into the Resource Packs menu (ingame) and click "Open Resource Pack folder" then navigate upward one level to get to the main Foolcraft 3 folder. Have a look in "Crash Reports" for the latest crash report.

Also I don't really know if that error is a problem or not. Probably fine to ignore it if it's just printing to chat tho.

_PS: Great generator idea_ 😉

**Comment by Moukit13** [comment]
It's a dead stop crash. drops me off in a white out storm in Antarctica per se :3 and i thought java might make one? because the windows crash handler sends something to Microsoft.
And that is a good idea :3 but if i do that, i'm likely to continue to modify it in the future XD i mean-- i could pass it as fanart if i posted it on twitch XD

PS there's another way to get to the file, in twitch if you view the profile you can clock on a gear shaped button and hit "Open folder." and i think you may be right, i'm seeing crash reports for the bag of holding- the thing dropped form a chance cube and eventually decided to eat my gear x.x,- the minimoo crashes, and then one that i can't figure out what's from. maybe it was one of the times my computer itself crashed, if that's even possible. (something's wrong with the video memory.) dunno, pasting it here, see if it makes any sense to you.
[crash-2019-09-12_16.14.52-client.txt](https://github.com/scalda/Foolcraft_3/files/3631444/crash-2019-09-12_16.14.52-client.txt)
Thanks a ton!

**Comment by Revvilo** [comment]
Ah ok. I've had a look and found that the problem is probably just an infinite loop which means the game isn't 'crashing' but rather 'freezing' - meaning no crash report.
Vanillafix generates a lot of other 'crash' reports for things and the one you posted looks to be one of those. I'm not seeing anything connected to mods in there so it's probably unrelated, as you have said.

But yeah, if you need that snowball thing fixed the only way would probably be to update Extra Utilities (I think I said Thermal Expansion before, whoopsie)
Check it out! There's an update specifically for this bug. It's now the latest update I believe:
<img src="https://user-images.githubusercontent.com/13816212/65366328-8a890d00-dc76-11e9-9ed3-0d0c5eb96ff6.png" width=300px>

Anyway, I hope that gets you on your way, and also yea, there's plenty of ways to get to the folder hehe, I just generally suggest the method which requires the least amount of tech support.

**Comment by Moukit13** [comment]
ok cool. i'll take that into consideration. i hope you have a wonderful day and tysm for the help!
