### ISSUE TITLE
Moofluid cow crash

### ISSUE THREAD

**Issue by Moukit13** [scalda/Foolcraft_3#354]
## Issue Description
i can't milk the EXP cow and i'm gonna have to figure out how to load backups, because i decided to try using a rancher on it >.< (both end up with a crash that vanillafix pulls you out of, however when vanillafix pulls you out, not only does it save the world, but you can't reopen the world unless you restart your game from my experience. Please tell me how to stop vanillafix, so i don't have a similar problem to my current rancher&cow permacrashed world.) i copied the crash report from pastebin into a text file here, but the link is in additional info. i only know where to find this report because vanillafix offered it to me lol >.<

[crash.txt](https://github.com/scalda/Foolcraft_3/files/3626668/crash.txt)

## Reproduce Steps
Find a liquid exp fluid moo (i used an angel crystal to make it originally)
right click it with a bucket, or use a rancher on it. (from thermal expansion i think?)
WATCH THE WORLD BURN-- JK, but it will cease to exist for a little while XD

## Additional Information
https://paste.dimdev.org/ebaresigob.mccrash

**Comment by Revvilo** [comment]
Good news: I'm pretty sure you can fix your world.
Bad news: This won't be fixed in the pack because Foolcraft 3 is no longer developed, and Minimoos hasn't been updated (from what I can see.)

What's happened is that machine has attempted to milk the cow and somewhere along the line in Minimoos' code a divide by 0 error cropped up and crashed the game.

Here's what I hope will fix your world (you will lose the offending machine):
_This can all be done without restarting the game (as long as it doesn't crash to desktop)_
- On the main menu, click `Mods` and look for Forge in the list
- Click Forge then click the `Config` button
- Inside `General` look for `Remove Erroring Tile Entities` and set it to true
- Click done and all that, then attempt to load the world

No matter the outcome, make sure to set that setting to false afterward.
Let me know if that works or not :)

**Comment by Moukit13** [comment]
Oh, tysm! i'll have to test that, however i already loaded a previous save and deleted the errored one. BTW i found a way to replace that buggy cow anyways :3

 I have a wither skeleton in a mob duplicator, and I had looked at it in my survival world and thought "I can improve this." so i took it to a test world and made it not only self sustaining, but it's to the point that it creates more coal and exp than it can use! who needs an exp fluid moo? i'll probably look into doing this for other fluids eventually too XD no promises though.

here's the world file, with both the old, exp sucking version, and the modified productive version. 
[New World.zip](https://github.com/scalda/Foolcraft_3/files/3631337/New.World.zip)
Hope you have a wonderful day! I'm off to test your world-fix trick!

**Comment by Moukit13** [comment]
that was unexpected.

i opened a flat world, took a creative powercell, a fluid moo, an angel crystal(actually quite a few) a fluid trash can, an ender fluid pipe, and finally the offending block, the rancher.
_and..._
_it..._
![wtf](https://user-images.githubusercontent.com/55463779/65250362-751fb180-dac3-11e9-893a-42c7b4801280.PNG)
**WORKED**
![wtf setup](https://user-images.githubusercontent.com/55463779/65250382-7ea91980-dac3-11e9-9e47-6b18823e8cab.PNG)
what do i do now? XD

**Comment by Revvilo** [comment]
Weiiiirdddd. Maybe related to how the cows can have random stats?
If your world is fixed then I guess just play while avoiding the setup which crashed you, right?

**Comment by Moukit13** [comment]
I suppose so. perhaps it's that you can have a cow that makes multiple buckets of fluid at once? regardless, i think the safest bet is to just avoid fluid moos.

**Comment by Moukit13** [comment]
perhaps. maybe it has to do with the cows being able to have multiple buckets produced at once? regardless i think it would be better to use fluid cows instead of fluid moos. if you don't wanna risk crashing, avoid fluid moos. end of story XD

**Comment by Revvilo** [comment]
It has been reported on the issue tracker for MiniMoos, so once an update is released you could update that too if you decide to use that route.
https://github.com/RicardoTheCoder/MiniMoos/issues/30
