### ISSUE TITLE
Low tps

### ISSUE THREAD

**Issue by yamy19** [scalda/Foolcraft_3#93]
[x] I am running FoolCraft via Curse/Twitch Launcher
 [x] I am running the latest version of FoolCraft
 [x] I can reproduce this issue consistently
          [ ] In single player
          [x] In multiplayer
 [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously 
     fixed and I'm having the same problem.
 [ ] I am crashing and can provide my crash report(s)

SUGGESTION/HELP
 [ ]  I would like to propose an additional mod, config change, custom recipe, etc.
 [ ]  I am requesting help with installing or running the pack

**# Issue Description**

Yes the server I'm currently apart of I've been working with them to try to fix the tps we recently updated to the latest version of the modpack before we where getting a stabel 17-20 tps now since we've updated it's at a constant 4-5 tps we have lowers the render distance to 4 as perviously suggested from an old thread but to no luck.

**# Reproduce Steps**
It's just a constant thing

# **Additional Information**

https://m.imgur.com/sXFoOhm?r

Server specs
2x xeon E5620
64gb ddr3
about 8tb mechanical drive storage
256gb ssd

**Comment by Mrbysco** [comment]
Are the people on the server by any chance chunkloading through FTB utilities?

**Comment by yamy19** [comment]
Yes players are using ftb chunk loading

**Comment by yamy19** [comment]
We have lowers it to one ftb chunk loading at a time though

**Comment by yamy19** [comment]
Ok we have completely disabled ftb chunkloading

**Comment by theBluebaerry** [comment]
Hi there, one of the owners from the server yamy19 is speaking of. Even with ftb chunk loading totally disabled we still have low fps usually around 4-7.

**Comment by kpeckett** [comment]
FPS or TPS? FPS (frames per second - how well the client can render the game) is what you see in the F3 screen, and TPS (game ticks per second - how fast the server is running) is what shows when a player runs `/tps` in chat.

**Comment by yamy19** [comment]
It's tps

**Comment by theBluebaerry** [comment]
Woops sorry that was a typo, I meant to write tps.

**Comment by generrosity** [comment]
Scalda kindly included TickProfiler to the pack. 

Could I suggest maybe sharing some "/tps" and "/profile e" type commands for entities, CPU utilization, locks, etc etc (top list from the wiki https://github.com/MinimallyCorrect/TickProfiler/wiki )

I've been trying to find out more about the "CarpetMod" (server jar patch) as a better form of identifying where tick-time goes including stats for OS overhead, and if its something viable to run 'all the time'.

**Comment by yamy19** [comment]
[https://imgur.com/TlD7CE1](url)

**Comment by Mrbysco** [comment]
That Imgur url is invalid

**Comment by yamy19** [comment]
we have disabled rs for now to see if it helps and for other crash related issues from rs

**Comment by generrosity** [comment]
If my maths is right, 4.8tps is 205ms/t - which is the 15% from entities shown on screen.

I imagine you found a RS Controller at -3089,76,3329, and suggest the ppl at the 2nd/3rd/4rd chunk listed to light up their underground (AS cave illuminator for instance)

Doing a CPU '/profile u' might show things outside the server thread - mine shows dynmap there (the number looks you need to drop 4 decimals)

You could copy a backup into a single player world? You can kill the chunk loading mods one by one at that point, and confirm no other server influence (we had no vanilla recipes due to running under an odd service account)

**Comment by yamy19** [comment]
we probably just going to leave refined storage disable for now. because at this moment with disabled we are running at 16 to 20 tps with at the most 15 players on

**Comment by generrosity** [comment]
That is an awesome result!

I'm curious if that controller covered chunks border - iskallians saying avoid crossing borders at all!

**Comment by yamy19** [comment]
We not rlly sure all we know is when the players were using auto Crafters to build the RS peice for the condensor it would lag the hell out and drop the tps to 1-3

**Comment by Foolcraft3NZ** [comment]
I am the owner of this server in question. I have managed to solve this issue. I have found that people have made a base, full of machines and have it loaded 24/7. This issue may partially be also because of conduits etc passing through chunk boarders. I found it easier to fully disable chunk loading, solving the low TPS issue, and now have an average TPS of 19. To solve the angel ring issue I am having to make a community chunk loaded area to keep players mills running 24/7. Hardware is not an issue here, with 2x Xeon x5690 3.46Ghz CPU's and 30G Dedicated memory.
